package main

var sayingsEn = []string{
	"Let's see weather or not you should leave umbrella at home.",
	"The best and the worst thing about the weather is that it changes.",
	"Conversation about the weather is the last refuge of the unimaginative.",
	"Weather forecast for tonight: dark.",
	"There is no such thing as bad weather, only different kinds of good weather.",
	"I've lived in good climate, and it bores the hell out of me.",
	"Do you know that bad weather always looks worse through a window?",
}

var forecasts = map[string]string{
	"Now":     "current?",
	"2 days":  "forecast/hourly?hours=48&",
	"5 days":  "forecast/hourly?hours=120&",
	"10 days": "forecast/daily?",
}

var months = map[string]string{
	"01": "January",
	"02": "February",
	"03": "March",
	"04": "April",
	"05": "May",
	"06": "June",
	"07": "July",
	"08": "August",
	"09": "September",
	"10": "October",
	"11": "November",
	"12": "December",
}

var emojis = map[string]int{
	"Wind":         127788,
	"Thermometer":  127777,
	"Comet":        9732,
	"N":            11015,
	"E":            11013,
	"W":            10145,
	"S":            11014,
	"SE":           8598,
	"ESE":          8598,
	"SSE":          8598,
	"SW":           8599,
	"SSW":          8599,
	"WSW":          8599,
	"NW":           8600,
	"WNW":          8600,
	"NNW":          8600,
	"NE":           8601,
	"ENE":          8601,
	"NNE":          8601,
	"Balloon":      127880,
	"Check":        9989,
	"Warning":      9888,
	"Smoking":      128684,
	"Cross":        10060,
	"Question":     10067,
	"ThunderRain":  9928,
	"Thunder":      127785,
	"Umbrella":     9730,
	"UmbrellaRain": 9748,
	"CloudRain":    127783,
	"CloudSnow":    127784,
	"Saturn":       129680,
	"Fog":          127787,
	"Sun":          9728,
	"SunSCloud":    127780,
	"SunMCloud":    9925,
	"Cloud":        9729,
	"Up":           128316,
	"Down":         128317,
	"Dry":          129344,
	"Wet":          128167,
	"Low":          10549,
	"High":         10548,
}

var commentsEn = map[string]string{
	"no":                "👒 No danger to the average person.",
	"little":            "👓 Little risk of harm.",
	"high":              "☝ High risk of harm.",
	"vhigh":             "☝☝ Very high risk of harm.",
	"extreme":           "❌ Extreme risk of harm. Stay indors!",
	"hat":               "Wear a hat and/or sunglasses.",
	"spf15":             "Use SPF 15+ Sunscreen.",
	"spf30":             "Use SPF 30+ Sunscreen.",
	"spf50":             "Use SPF 50 Sunscreen.",
	"cover":             "Cover the body with clothing. Avoid the sun if possible.",
	"sunburn":           "Sun burn time is",
	"DefaultMessage":    "Hi! I am WeartheBot and I cannot spell.",
	"CoordsAccepted":    "Gotcha! Please choose the forecast period.",
	"BackToMainMenu":    "What interests you most now?",
	"AtMyLocation":      "Weather at my location",
	"AtADifferentPlace": "Weather elsewhere",
	"Back0":             "< Back",
	"Back1":             "<< Back",
	"ByDays":            "By Days",
	"ByHours":           "By Hours",
	"3Days":             "3 days",
	"5Days":             "5 days",
	"7Days":             "7 days",
	"10Days":            "10 days",
	"16Days":            "16 days",
	"24Hours":           "24 hours",
	"48Hours":           "48 hours",
	"72Hours":           "72 hours",
	"96Hours":           "96 hours",
	"120Hours":          "120 hours",
	"OnStop":            "Bye! Have a nice day!",
}
